pub mod gmimc;
pub mod instances;

pub use gmimc::{Gmimc, GmimcParams};
pub use instances::{
    GMIMC_BABYBEAR_16_PARAMS, GMIMC_BABYBEAR_24_PARAMS, GMIMC_BLS12_381_3_PARAMS,
    GMIMC_BN254_3_PARAMS, GMIMC_GOLDILOCKS_12_PARAMS, GMIMC_GOLDILOCKS_8_PARAMS,
    GMIMC_KOALABEAR_16_PARAMS, GMIMC_KOALABEAR_24_PARAMS, GMIMC_MERSENNE31_16_PARAMS,
    GMIMC_MERSENNE31_24_PARAMS,
};

#[cfg(test)]
mod test_vectors;
